# permissions for end users to view taskv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskv2-viewer-role
rules:
- apiGroups:
  - batch.platform.upstage.ai
  resources:
  - taskv2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.platform.upstage.ai
  resources:
  - taskv2s/status
  verbs:
  - get
