# permissions for end users to edit taskv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taskv2-editor-role
rules:
- apiGroups:
  - batch.platform.upstage.ai
  resources:
  - taskv2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.platform.upstage.ai
  resources:
  - taskv2s/status
  verbs:
  - get
